version: '3.9'

networks:
    laravel-network:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx_laravel
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel-network
    
    mysql:
        image: mysql:latest
        container_name: mysql_laravel
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: paroquia_10            
            MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
            SERVICE_TAG : dev
            SERVICE_NAME : mysql
        networks:
            - laravel-network
        volumes:
            - ./docker/mysql:/var/lib/mysql

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_laravel
        volumes:
            - ./src:/var/www/html
        ports:
            - "9004:9004"
        networks:
            - laravel-network

    composer:
        image: composer:latest
        container_name: composer_laravel
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - laravel-network

    npm:
        image: node:latest
        container_name: npm_laravel
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']

    artisan:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: artisan_laravel
        volumes: 
            - ./src:/var/www/html
        depends_on: 
            - mysql
        working_dir: /var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks: 
            - laravel-network
        
    phpmyadmin:
        image: phpmyadmin:latest
        links:
            - mysql
        container_name: phpmyadmin_laravel
        restart: always
        ports:
            - 88:80
        environment:
            - PMA_ARBITRARY=1 
        networks:
            - laravel-network

