version: "3.8"
volumes:
  data:
services:
  db:
    container_name: ${MYSQL_HOST}
    image: 'mysql:8.0'
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  
  admin:
    image: phpmyadmin/phpmyadmin:latest
    links:
     - db:${MYSQL_HOST}
    depends_on:
     - db
    ports:
     - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: "3306"
      PMA_ARBITRARY: 1
